import { useEffect, useState, type ReactNode } from 'react';
import { api, type WorkCard, type WorkgraphAttention, type WorkgraphLearning, type WorkgraphMeasurement } from '../api';

export default function WorkgraphView() {
  const [cards, setCards] = useState<WorkCard[] | null>(null);
  const [measurement, setMeasurement] = useState<WorkgraphMeasurement | null>(null);
  const [attention, setAttention] = useState<WorkgraphAttention[] | null>(null);
  const [learning, setLearning] = useState<WorkgraphLearning | null>(null);
  const [selected, setSelected] = useState<Record<string, unknown> | null>(null);
  useEffect(() => { Promise.all([api.getWorkCards(), api.getWorkgraphAttention(), api.getWorkgraphLearning()]).then(([work, queue, learning]) => { setCards(work.cards); setMeasurement(work.measurement); setAttention(queue.attention); setLearning(learning); }).catch(() => setCards([])); }, []);
  if (!cards) return <p className="text-[13px]" style={{ color: 'var(--helicon-muted)' }}>Reading connected work records…</p>;
  if (!cards.length) return <div className="py-14 text-center"><h3 className="text-[22px]" style={{ fontFamily: 'var(--helicon-serif)' }}>No Work Cards yet</h3><p className="mt-2 text-[13px]" style={{ color: 'var(--helicon-muted)' }}>Work Cards join Helicon’s existing memory, context, skills, and run records when a real outcome needs evidence.</p></div>;
  return <><div className="grid grid-cols-2 sm:grid-cols-4 gap-2 mb-3">{measurement && [['Work', measurement.work_cards], ['Linked runs', measurement.linked_runs], ['Frozen context', measurement.context_packets], ['Context with memory', measurement.context_with_memory]].map(([label, value]) => <div key={String(label)} className="rounded-lg border bg-white px-3 py-2" style={{ borderColor: 'var(--helicon-line)' }}><div className="text-[18px]" style={{ fontFamily: 'var(--helicon-serif)' }}>{value}</div><div className="text-[9px] uppercase tracking-[.12em]" style={{ color: 'var(--helicon-muted)' }}>{label}</div></div>)}</div>{measurement && <p className="mb-3 text-[10px]" style={{ color: 'var(--helicon-muted)' }}>Coverage of linked Work Cards · {measurement.cards_with_skills} with skills · {measurement.reviewed_skill_versions}/{measurement.declared_skills} instruction snapshots · {measurement.cards_with_artifacts} with artifacts · {measurement.verified_runs} verified · {measurement.runs_with_wall_elapsed}/{measurement.linked_runs} wall time · {measurement.runs_with_token_usage}/{measurement.linked_runs} token usage</p>}{learning && <section className="mb-5 rounded-xl border bg-white p-4" style={{ borderColor: 'var(--helicon-line)' }}><p className="text-[10px] uppercase tracking-[.15em]" style={{ color: 'var(--helicon-muted)' }}>Outcome learning</p><p className="mt-1 text-[13px]" style={{ color: 'var(--helicon-ink)' }}>{learning.recommendations_withheld ? `Withheld · ${learning.resolved_work_cards}/${learning.evidence_floor} resolved Work Cards per observed group` : 'Observed outcome evidence is available; inspect its provenance before changing routing.'}</p><p className="mt-1 text-[11px]" style={{ color: 'var(--helicon-muted)' }}>Harness, model, and skill patterns remain observations—not causal claims.</p></section>}{attention !== null && <section className="mb-5 rounded-xl border bg-white p-4" style={{ borderColor: 'var(--helicon-line)' }}><p className="text-[10px] uppercase tracking-[.15em]" style={{ color: 'var(--helicon-muted)' }}>Attention queue · missing record edges</p>{attention.length ? <div className="mt-3 space-y-2">{attention.slice(0, 4).map(item => <button key={`${item.wager_id}-${item.action}`} onClick={() => api.getWorkCardTrace(item.wager_id).then(setSelected)} className="block w-full text-left"><span className="text-[10px] uppercase tracking-[.12em]" style={{ color: item.priority === 'now' ? 'var(--helicon-ink)' : 'var(--helicon-muted)' }}>{item.priority} · {item.action.replaceAll('_', ' ')}</span><span className="ml-2 text-[12px]" style={{ color: 'var(--helicon-ink)' }}>{item.reason}</span></button>)}</div> : <p className="mt-2 text-[12px]" style={{ color: 'var(--helicon-muted)' }}>No missing Work Graph edges are currently recorded.</p>}</section>}<div className="grid gap-4 lg:grid-cols-[1.15fr_.85fr]">
    <div className="space-y-3">{cards.map(card => <button key={card.id} onClick={() => api.getWorkCardTrace(card.id).then(setSelected)} className="w-full text-left rounded-xl border p-4 bg-white hover:bg-stone-50" style={{ borderColor: 'var(--helicon-line)' }}>
      <div className="flex justify-between gap-3 text-[10px] uppercase tracking-[.15em]" style={{ color: 'var(--helicon-muted)' }}><span>{card.outcome || 'outcome pending'}</span><span>{card.next_action || 'needs a move'}</span></div>
      <h3 className="mt-1 text-[18px] leading-snug" style={{ fontFamily: 'var(--helicon-serif)', color: 'var(--helicon-ink)' }}>{card.intent}</h3>
      <p className="mt-1 text-[12px]" style={{ color: 'var(--helicon-muted)' }}>{card.beneficiary} · {card.observable_change}</p>
      <div className="mt-3 flex gap-3 text-[10px]" style={{ color: 'var(--helicon-muted)' }}><span>{card.model || 'no run'}{card.harness ? ` · ${card.harness}` : ''}</span><span>{card.context_items || 0} context</span><span>{card.evidence_count} receipts</span></div>
    </button>)}</div>
    <aside className="rounded-xl border p-4 bg-white min-h-48" style={{ borderColor: 'var(--helicon-line)' }}><p className="text-[10px] uppercase tracking-[.15em]" style={{ color: 'var(--helicon-muted)' }}>Connected record</p>{selected ? <Trace trace={selected} /> : <p className="mt-3 text-[13px]" style={{ color: 'var(--helicon-muted)' }}>Select a Work Card to inspect the actual links—context/memory, skills, run, artifacts, evidence, and next moves.</p>}</aside>
  </div></>;
}

function Trace({ trace }: { trace: Record<string, unknown> }) {
  const card = trace.work_card as Record<string, unknown> | undefined;
  const run = trace.task_run as Record<string, unknown> | null;
  const packet = trace.context_packet as Record<string, unknown> | null;
  const skills = (trace.skills as string[]) || [];
  const reviews = (trace.skill_reviews as { skill_version: string; content_hash: string }[]) || [];
  const evidence = (trace.outcome_evidence as Record<string, unknown>[]) || [];
  const executionEvidence = (trace.execution_evidence as Record<string, unknown>[]) || [];
  const moves = (trace.next_moves as Record<string, unknown>[]) || [];
  const timeline = (trace.timeline as { at: string; kind: string; label: string }[]) || [];
  const section = (name: string, body: ReactNode) => <div className="mt-4"><p className="text-[9px] uppercase tracking-[.15em]" style={{ color: 'var(--helicon-muted)' }}>{name}</p><div className="mt-1 text-[11px] leading-relaxed" style={{ color: 'var(--helicon-ink)' }}>{body}</div></div>;
  return <div>
    {section('Outcome contract', <><div>{String(card?.intent || '—')}</div><div style={{ color: 'var(--helicon-muted)' }}>{String(card?.beneficiary || '—')} · {String(card?.outcome || 'pending')}</div></>)}
    {section('Run', run ? <>{String(run.model || 'unknown model')} · {String(run.harness || 'unknown harness')}<br/><span style={{ color: 'var(--helicon-muted)' }}>{String(run.verification_outcome || 'verification pending')}</span></> : <span style={{ color: 'var(--helicon-muted)' }}>No TaskRun linked yet.</span>)}
    {section('Context & memory', packet ? <>{String((packet.included_memory_items as unknown[])?.length || 0)} safe memory items · {String(packet.token_estimate || 0)} tokens<br/><span style={{ color: 'var(--helicon-muted)' }}>{String(packet.excluded_relevant_count || 0)} relevant items withheld by policy</span></> : <span style={{ color: 'var(--helicon-muted)' }}>No frozen packet linked yet.</span>)}
    {section('Skills', skills.length ? <>{skills.map(skill => <div key={skill}>{reviews.some(review => review.skill_version === skill) ? 'reviewed' : 'needs review'} · {skill}</div>)}</> : <span style={{ color: 'var(--helicon-muted)' }}>No declared skill versions.</span>)}
    {section('Outcome evidence', evidence.length ? evidence.map((e, i) => <div key={i}>{String(e.kind)} · {String(e.reference)}</div>) : <span style={{ color: 'var(--helicon-muted)' }}>No beneficiary/world receipt yet.</span>)}
    {section('Execution evidence', executionEvidence.length ? executionEvidence.map((e, i) => <div key={i}>{String(e.kind)} · {String(e.reference)}</div>) : <span style={{ color: 'var(--helicon-muted)' }}>No execution receipt yet.</span>)}
    {section('Next move', moves.length ? <>{String(moves[0].action)} · {String(moves[0].status)}<br/><span style={{ color: 'var(--helicon-muted)' }}>{String(moves[0].rationale)}</span></> : <span style={{ color: 'var(--helicon-muted)' }}>No move recorded.</span>)}
    {section('Record timeline', timeline.length ? timeline.slice(-8).map((event, i) => <div key={`${event.at}-${i}`}><span style={{ color: 'var(--helicon-muted)' }}>{event.at?.slice(0, 16).replace('T', ' ') || '—'}</span> · {event.label}</div>) : <span style={{ color: 'var(--helicon-muted)' }}>No dated record events.</span>)}
  </div>;
}
